const categories = [
    {
        'name': 'Rau củ quả',
        'url': 'https://i.imgur.com/csTN0VX.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'code': 'RCQ',
        'note': 'write something here',
        'subcategories_1': [
            'Tất cả',
            'Cần tây nhỏ',
            'Sup lơ xanh',
            'Củ cải đỏ',
            'Măng tây giống Nhật',
            'Loại khác',
        ],
    },
    {
        'name': 'Nấm',
        'url': 'https://i.imgur.com/l7nve2R.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'code': 'NAM',
        'note': 'write something here',
        'subcategories_1': [
            'Tất cả',
            'Nấm sò trắng',
            'Nấm sò xám',
            'Nấm mối tươi',
            'Loại khác',
        ],
    },
    {
        'name': 'Cây ăn trái',
        'url': 'https://i.imgur.com/Dlge9zD.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'code': 'CAT',
        'note': 'write something here',
        'subcategories_1': [
            'Tất cả',
            'Bơ',
            'Sầu riêng',
            'Chuối',
            'Loại khác',
        ],
    },
    {
        'name': 'Các loại hạt',
        'url': 'https://i.imgur.com/btWrZwF.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'code': 'CLH',
        'note': 'write something here',
        'subcategories_1': [
            'Tất cả',
            'Đậu đỏ',
            'Vừng/ mè',
            'Hạt điều',
            'Loại khác',
        ],
    },
    {
        'name': 'Lúa gạo',
        'url': 'https://i.imgur.com/wHh2i4v.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'code': 'LGAO',
        'note': 'write something here',
        'subcategories_1': [
            'Tất cả',
            'Gạo Tám Xoan',
            'Gạo ST24',
            'Gạo Hàm Châu',
            'Loại khác',
        ],
    },
    {
        'name': 'Lúa nếp',
        'url': 'https://i.imgur.com/zJzDrXv.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'code': 'LNEP',
        'note': 'write something here',
        'subcategories_1': [
            'Tất cả',
            'Nếp cái hoa vàng',
            'Nếp nhung',
            'Nếp nương',
            'Loại khác',
        ],
    },
    {
        'name': 'Cây công nghiệp',
        'url': 'https://i.imgur.com/zJzDrXv.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'code': 'CCN',
        'note': 'write something here',
        'subcategories_1': [
            'Tất cả',
            'Hồ tiêu',
            'Điều',
            'Macca',
            'Loại khác',
        ],
    },
    {
        'name': 'Hải sản',
        'url': 'https://i.imgur.com/zJzDrXv.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'code': 'HSAN',
        'note': 'write something here',
        'subcategories_1': [
            'Tất cả',
            'Ghẹ',
            'Mực',
            'Nghêu',
            'Loại khác',
        ],
    },
    {
        'name': 'Gia cầm',
        'url': 'https://i.imgur.com/zJzDrXv.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'code': 'GCAM',
        'note': 'write something here',
        'subcategories_1': [
            'Tất cả',
            'Ngan',
            'Ngỗng',
            'Cút',
            'Loại khác',
        ],
    },
    {
        'name': 'Rong biển',
        'url': 'https://i.imgur.com/zJzDrXv.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'code': 'RBIEN',
        'note': 'write something here',
        'subcategories_1': [
            'Tất cả',
            'Rong biển Kanten',
            'Tảo bẹ',
            'Rong biển WAKAME',
            'Loại khác',
        ],
    },
    {
        'name': 'Dược liệu',
        'url': 'https://i.imgur.com/zJzDrXv.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'code': 'DLIEU',
        'note': 'write something here',
        'subcategories_1': [
            'Tất cả',
            'Hoàng liên chân gà',
            'Cây bình vôi',
            'Vành đắng',
            'Loại khác',
        ],
    },
    {
        'name': 'Hoa - cây cảnh',
        'url': 'https://i.imgur.com/zJzDrXv.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'code': 'HCC',
        'note': 'write something here',
        'subcategories_1': [
            'Tất cả',
            'Hoa mai',
            'Hoa cúc',
            'Hoa ly',
            'Loại khác',
        ],
    },
];

export default categories;
