const subCategories1 = {
    'Cần tây nhỏ': {
        'url': 'https://i.imgur.com/tI7NSnH.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'RCQ-CTN',
    },
    'Sup lơ xanh': {
        'url': 'https://i.imgur.com/Ax1tz6Y.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'RCQ-SLX',
    },
    'Củ cải đỏ': {
        'url': 'https://i.imgur.com/aLIcc3q.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'RCQ-CCD',
    },
    'Măng tây giống Nhật': {
        'url': 'https://i.imgur.com/JDboU4j.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'RCQ-MTGN',
    },
    'Nấm sò trắng': {
        'url': 'https://i.imgur.com/CmjmE72.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'NAM-NST',
    },
    'Nấm sò xám': {
        'url': 'https://i.imgur.com/prdlPBQ.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'NAM-NSX',
    },
    'Nấm mối tươi': {
        'url': 'https://i.imgur.com/gKxmQym.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'NAM-NMT',
    },
    'Bơ': {
        'url': 'https://i.imgur.com/qn0ZiY7.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'CAT-BO',
    },
    'Sầu riêng': {
        'url': 'https://i.imgur.com/eGaZV9y.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'CAT-SRIENG',
    },
    'Chuối': {
        'url': 'https://i.imgur.com/warcAMD.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'CAT-CHUOI',
    },
    'Đậu đỏ': {
        'url': 'https://i.imgur.com/T81AJ3T.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'CLH-DDO',
    },
    'Vừng/ mè': {
        'url': 'https://i.imgur.com/NjuPpdJ.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'CLH-ME',
    },
    'Hạt điều': {
        'url': 'https://i.imgur.com/yVdYpbl.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'CLH-HDIEU',
    },
    'Gạo Tám Xoa': {
        'url': 'https://i.imgur.com/jPWAKA5.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'LGAO-GTX',
    },
    'Gạo ST24': {
        'url': 'https://i.imgur.com/XjILnfp.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'LGAO-ST24',
    },
    'Gạo Hàm Châu': {
        'url': 'https://i.imgur.com/zstpojD.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'LGAO-GHC',
    },
    'Nếp cái hoa vàng': {
        'url': 'https://i.imgur.com/9aAqH9R.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'LNEP-NCHV',
    },
    'Nếp nhung': {
        'url': 'https://i.imgur.com/hrUp3f6.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'LNEP-NHUNG',
    },
    'Nếp nương': {
        'url': 'https://i.imgur.com/MAjB7us.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'LNEP-NUONG',
    },
    'Hồ tiêu': {
        'url': 'https://i.imgur.com/gXKniP8.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'CCN-HTIEU',
    },
    'Điều': {
        'url': 'https://i.imgur.com/K3pma24.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'CCN-DIEU',
    },
    'Macca': {
        'url': 'https://i.imgur.com/ObyFmve.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'CCN-MACCA',
    },
    'Ghẹ': {
        'url': 'https://i.imgur.com/YnwsZJV.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'HSAN-GHE',
    },
    'Mực': {
        'url': 'https://i.imgur.com/cs7RXum.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'HSAN-MUC',
    },
    'Nghêu': {
        'url': 'https://i.imgur.com/mLbOjVO.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'CCN-NGHEU',
    },
    'Ngan': {
        'url': 'https://i.imgur.com/nrxIQOR.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'GCAM-NGAN',
    },
    'Ngỗng': {
        'url': 'https://i.imgur.com/k3Am1wc.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'CCN-NGONG',
    },
    'Cút': {
        'url': 'https://i.imgur.com/AmkcIft.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'CCN-CUT',
    },
    'Rong biển Kanten': {
        'url': 'https://i.imgur.com/clKySPW.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'RBIEN-RBKTEN',
    },
    'Tảo bẹ': {
        'url': 'https://i.imgur.com/KiAkZCP.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'RBIEN-TBE',
    },
    'Rong biển WAKAME': {
        'url': 'https://i.imgur.com/sgATPvg.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'RBIEN-RBWAKAME',
    },
    'Hoàng liên chân gà': {
        'url': 'https://i.imgur.com/clKySPW.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'DLIEU-HLCG',
    },
    'Cây bình vôi': {
        'url': 'https://i.imgur.com/KiAkZCP.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'DLIEU-BVOI',
    },
    'Vành đắng': {
        'url': 'https://i.imgur.com/sgATPvg.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'DLIEU-VDANG',
    },
    'Hoa mai': {
        'url': 'https://i.imgur.com/clKySPW.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'HCC-MAI',
    },
    'Hoa cúc': {
        'url': 'https://i.imgur.com/KiAkZCP.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'HCC-HCUC',
    },
    'Hoa ly': {
        'url': 'https://i.imgur.com/sgATPvg.png',
        'url_thumbnail': 'https://i.imgur.com/HCPYKhW.jpg',
        'note': 'write something here',
        'code': 'HCC-HLY',
    },
};

export default subCategories1;
